name: auto-assign-pr-reviewer
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: on PR creation
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr edit ${{github.event.pull_request.html_url}} \
            --add-reviewer simcard0000,janakitti
